channels:
  - conda-forge
  - defaults

dependencies:
  # General dev tools
  - pre-commit
  # C++ dev tools
  - make
  - cmake>=3.15
  - clang-tools=10
  - conan
  - ccache
  # C++ runtime dependency
  - scip
  # Build time Python dependencies
  - python>=3.6
  - pybind11>=2.6
  - numpy>=1.4
  - xtensor-python
  # Python runtime dependency
  - pyscipopt >= 3.0.1  # optional
  # Python dev tools
  - ipython
  - pytest
  - black
  # Documentation
  - doxygen
  - sphinx>=3.0
  - breathe>=4.15
  - sphinx_rtd_theme
